name: myportfolio
description: A Spider-Man themed portfolio website built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.2.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.6
  particles_flutter: ^0.1.4
  vector_math: ^2.1.4
  rive: ^0.11.4
  model_viewer_plus: ^1.7.0
  flutter_staggered_animations: ^1.1.1
  meta_seo: ^3.0.9

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.14.4

# Flutter specific configuration
flutter:
  uses-material-design: true
  assets:
    - assets/models/

# Android configuration
android:
  enable_android_embedding_v2: true
  enable_impeller: true
  
# iOS configuration
ios:
  supports_storyboard: true

# Flutter launcher icons configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
  macos:
    generate: true
    image_path: "assets/images/icon.png"
  linux:
    generate: true
    image_path: "assets/images/icon.png"
